// Unified exports for the design system
export {
  Badge,
  Button,
  Card,
  Divider,
  EmptyState,
  EmptySearch,
  EmptyJournal,
  FloatingActionButton,
  Input,
  ListItem,
  Modal,
  ProgressBar,
  SobrietyCounter,
  TextArea,
  Text,
  Toast,
  Toggle,
  AnimatedCheckmark,
  GlassCard,
  GradientButton,
  GlassListItem,
  SwipeableListItem,
  BottomSheet,
  CircularProgress,
  PullToRefresh,
  ContextMenu,
  BreathingCircle,
  Skeleton,
  SkeletonCard,
  SkeletonListItem,
  SkeletonStats,
  SkeletonHome,
  SkeletonList,
  ConfettiCelebration,
  MilestoneCelebration,
  ParallaxHeader,
  ParallaxScrollView,
  StickyHeader,
  AnimatedCheckbox,
  AnimatedToggle,
  AnimatedRadio,
  SuccessCheckmark,
  AnimatedCounter,
  FavoriteButton,
  BouncingBadge,
  ThemeToggle,
  CompactThemeToggle,
  AsyncImage,
  Avatar,
  ZoomableImage,
  SearchExperience,
  FilterChip,
  SearchResultsHeader,
  HighlightedText,
  ScreenReaderText,
  AccessibleButton,
  Focusable,
  AccessibleField,
  AccessibleProgress,
  LiveRegion,
  SkipLink,
  Heading,
  AccessibleList,
  AccessibleListItem,
  announce,
  isScreenReaderEnabled,
  // New themed components
  AmberButton,
  TealCard,
  SageCard,
  LavenderCard,
  GoldButton,
  // Illustration System
  Illustration,
  OnboardingIllustration,
  BadgeIllustration,
  EmptyStateIllustration,
} from './components';

export { ThemeProvider } from './context/ThemeContext';
export { useTheme, useColors, useIsDark } from './hooks/useTheme';
export { useMotionPress } from './hooks/useMotionPress';
export { Action, useActionMotion } from './primitives';
export { ScreenAnimations } from './tokens/screen-animations';
export {
  serene,
  sereneGlow,
  serenePillRow,
  sereneRing,
  premiumTypographyAliases,
  backgroundTexture,
  getSereneProgressBarStyles,
  getSereneRingMetrics,
  getSereneTextureOverlay,
} from './tokens/serene';
export { MotionTransitions, motionDuration, motionSpring, motionScale, motionTiming, motionShimmer } from './tokens/motion';
export { glass, glow, glassGradients } from './tokens/glass';
export {
  aestheticColors,
  gradients,
  atmosphericShadows,
  aestheticTypography,
  aestheticSpacing,
  aestheticRadius,
  calmingMotion,
  premiumEffects,
  componentPatterns,
} from './tokens/aesthetic';
export { useTheme as useThemeTokens, darkColors, lightColors, spacing as themeSpacing, typography as themeTypography, borderRadius as themeBorderRadius } from './tokens/theme';
export type { Theme } from './tokens/theme';
export type { ActionRootProps, UseActionMotionOptions } from './primitives';
export {
  pressAnimation,
  hoverAnimation,
  successAnimation,
  attentionAnimation,
  loadingAnimation,
  breathingAnimation,
  usePressAnimation,
  useHoverAnimation,
  useSuccessAnimation,
  useAttentionAnimation,
  useShimmerAnimation,
  useBreathingAnimation,
  useStaggerAnimation,
} from './tokens/micro-animations';

export type {
  BadgeProps,
  ButtonProps,
  CardProps,
  DividerProps,
  EmptyStateProps,
  FloatingActionButtonProps,
  InputProps,
  ListItemProps,
  Milestone,
  ModalAction,
  ModalProps,
  ModalVariant,
  ProgressBarProps,
  SobrietyCounterProps,
  TextAreaProps,
  TextProps,
  ToastProps,
  ToastVariant,
  ToggleProps,
  AnimatedCheckmarkProps,
  GlassCardProps,
  GradientButtonProps,
  GlassListItemProps,
  SwipeableListItemProps,
  SwipeAction,
  BottomSheetProps,
  CircularProgressProps,
  PullToRefreshProps,
  ContextMenuProps,
  ContextMenuItem,
  BreathingCircleProps,
  SkeletonProps,
  AsyncImageProps,
  AvatarProps,
  ZoomableImageProps,
  // New themed component types
  AmberButtonProps,
  TealCardProps,
  SageCardProps,
  LavenderCardProps,
  GoldButtonProps,
  IllustrationProps,
} from './components';
